set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix C-z
bind-key C-z send-prefix

# Vim like pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# unbind %
# bind | split-window -h -c "#{pane_current_path}"

# unbind '"'
# bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Change from 0 based to 1 based because keyboard layout
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Vim-like copy/paste
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Alt+hjkl to switch panes (vim-style)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Alt+number to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n S-Left previous-window
bind -n S-Right next-window

RED="#ea6962"
GREEN="#a9b665"
YELLOW="#d8a657"
BLUE="#7daea3"
MAGENTA="#d3869b"
CYAN="#89b482"
BLACK="#1d2021"
DARK_GRAY="#32302f"
LIGHT_GRAY="#4f4946"
BG="#32302f"
FG="#d4be98"

HALF_ROUND_OPEN="#(printf '\ue0b6')"
HALF_ROUND_CLOSE="#(printf '\ue0b4')"
TRIANGLE_OPEN="#(printf '\ue0b2')"
TRIANGLE_CLOSE="#(printf '\ue0b0')"

# Status bar
set -g status "on"
set -g status-position "top"
set -g status-style bg=${BG},fg=${FG}
set -g status-justify absolute-centre
set -g status-left-length "100"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${CYAN},bg=${LIGHT_GRAY},align=centre"
set -g message-command-style "fg=${CYAN},bg=${LIGHT_GRAY},align=centre"

# Panes
set -g pane-border-style "fg=${LIGHT_GRAY}"
set -g pane-active-border-style "fg=${BLUE}"

# Windows
set -g window-status-separator ""

# Statusline - current window
set -g window-status-current-format "\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_OPEN}\
#[bg=${LIGHT_GRAY},fg=default]#I\
#[fg=${MAGENTA}]:\
#[fg=default]#W\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_CLOSE}\
"

# Statusline - other windows
set -g window-status-format "\
 \
#I\
#[fg=${MAGENTA}]:\
#[fg=default]#W \
"

# Statusline - right side
set -g status-right "\
#[fg=${LIGHT_GRAY},bg=default]${TRIANGLE_OPEN}\
#[bg=${LIGHT_GRAY},fg=${CYAN}] #h\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_CLOSE}\
"

# Statusline - left side (empty)
set -g status-left "\
#[fg=${LIGHT_GRAY},bg=default]${HALF_ROUND_OPEN}\
#[bg=${LIGHT_GRAY},fg=${YELLOW}]#S \
#[fg=${LIGHT_GRAY},bg=default]${TRIANGLE_CLOSE}\
"

# Modes
set -g clock-mode-colour "${GREEN}"
set -g mode-style "fg=${BLUE} bg=${DARK_GRAY} bold"

