# /etc/kmscon/kmscon.conf

# カスタムパレットの有効化
palette=custom

# --------------------------------------------------
# Gruvbox Dark (Medium) パレット設定
# --------------------------------------------------
# 背景色と文字色 (Dark 2 と Light 1)
palette-background=40,40,40
palette-foreground=235,219,178

# 標準16色 (ANSI 0 ~ 7)
palette-black=40,40,40          # bg0
palette-red=204,36,29           # red
palette-green=152,151,26        # green
palette-yellow=215,153,33       # yellow
palette-blue=69,133,136         # blue
palette-magenta=177,98,134      # purple
palette-cyan=104,157,106        # aqua
palette-white=168,153,132       # gray

# 明るい色 (ANSI 8 ~ 15)
palette-dark-grey=146,131,116 # gray
palette-light-red=251,73,52     # red (bright)
palette-light-green=184,187,38  # green (bright)
palette-light-yellow=250,189,47 # yellow (bright)
palette-light-blue=131,165,152  # blue (bright)
palette-light-magenta=211,134,155 # purple (bright)
palette-light-cyan=142,192,124  # aqua (bright)
palette-light-grey=235,219,178 # fg1
